sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: v0owaFstZW26ER7sTGdg2Wfn7madKgREgiZBxlKl9sXKwohpio+MJ73O9FRrOMYEyqi8EE9wZbji29gBp4RLZ/Vc/hYLoYnX/v9QB0Tt2dkQeraJhPyiDq2v/3reWaGqMqKqleS1Hr2z84dUOG5FpVEOQu7gfyKkkUpuSHXrfFaUtd9NYKNvjQOHE9q0e1h1viLK8o34gR2vnR4+R+JTWuEF6WrUeMGmRQyBCMd1AmhwfMB3o+Kdd1/S8Zd9k9Jte7O4L+yzfOCzqPKsPsmASyROC47V3nGRORImr0Szq7AY9gHLr5JWZSATisK1l+ew8qtUqHyxmt6AbzH4jvNoVYr4OgP8kmukoPa3Q+RTaVObM3nYT89lRp2/DtvrQQgtJLADjNR5eMIVlJBcI4eJ+jkrhu/HIEeKzknCvEydiNpkbo6mU4I9Odfu5BsDG1E6jjTgmWKE/WA1y+JJ0fDuI+s17NxwcX0IWlCqmIprch1jiMtheG9mqRjIUbARslts6nG1RJsWgOeGqDIPY5B3+8rDbVWrU/Jlz4UwJ8QuxFVPO5jwFCLpyraU/EFVo9E+R06qDhNQoTzQqg1umaPXyGUjiRLI1m+LUiUD8s3KFt0nXuUaEN0VYDW0TXDT712eyi+qndJ47n921EPmhgOSeAqL8d8MHI8l+mejOiziv3w=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: WAcbICawyWKW+N5JSzl+QX+RNQ5WjTQsVaLimS+obggIke3G54bRII6TxzdnZvP98BGWIfgXfKZ1mf6A+PUsvNmxAMhZzDuKpTcjtSpjRjrezsgN7Rw5Dux6GKRY8/CnoK/M6CeOjSUzVava17CsMYtQb5a8OI7YSbObmbDK1wFM+XQkLsv8HjM+eb2FsjrpGZ//j2Hx7r4EHue1TuPhjuZf97Wcj0HPhrBurgIfQDLFKKS4xXBz6dH6ZGiIs/wnO4PRHUhm+tnroMHV1u0p2aSL4EmJk3m3jyRFKIIGbmgSaxKZ3Yt9pDjcKVBmT8VLnL0OYYlRO9utIp1Yl+4Bg/Q77cxjrL0obYipqFdlyBbApj7zdNVHzCHipA3xPizqt+muQ7WFPxVswYzoDdJo/Z3VavNl5J/W5F9ITI8Owo7FH3/sQlhfaxVCf0RGu0UTA2MJvs5Wt0IioOyVub4VOf/CePVHUcxmi/HLqXikZfIPunrEVHoczIk2SprXmoV/qFiGLsbYpj+vXsd2FD+3/3FyYH0eBpRloGME/oyruK2qAB5ZnH3X2Cs5Eh5sZDHvnyljcgQbJYTuWMNt5UvbCGlYmEj0TwtntKh7EtEBZ26MqHCV6y3Q3QUlJooaXgto3Jyd0WN3L7hsmkBXdN9yIGaNIeJU78gZxqL1A8XtMtQ=
